server:
  port: 8000

eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
    service-url:
      defaultZone: http://172.31.47.195:8761/eureka
  instance:
    hostname: gateway-api
    prefer-ip-address: true


spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      globalcors:
       corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true   #추가
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
            exposedHeaders:
              - Authorization
              - RefreshToken 
      routes:
        - id: mentor-service
          uri: http://localhost:8080/mentors
          predicates:
            - Path=/mentors/**

